{
    "_Type": "Action.Type.ODataService.CreateEntity",
    "Target": {
        "EntitySet": "MyWorkOrderTools",
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "Properties": {
        "PRTCategory": "E",
        "Description": "/ZDSBSSAM/Rules/Operations/PRT/ZPRTDescription.js",
        "OrderId": "#Property:OrderId",
        "OperationNo": "#Property:OperationNo",
        "Equipment": "#Control:EquipmentLstPkr/#SelectedValue",
        "UsageValue": 0,
        "UsageUOM": "",
        "ControlKey": "#Control:ControlKeyLstPkr/#SelectedValue",
        "ItemCounter": "/SAPAssetManager/Rules/WorkOrders/Operations/PRT/CreateUpdate/PRTItemCounter.js",
        "ItemCounterChar": "/SAPAssetManager/Rules/WorkOrders/Operations/PRT/CreateUpdate/PRTItemCounterChar.js"
    },
    "Headers": {
        "OfflineOData.RemoveAfterUpload": "true",
        "OfflineOData.TransactionID": "#Property:OrderId"
    },
    "CreateLinks": [
        {
            "Property": "WOOperation_Nav",
            "Target": {
                "EntitySet": "MyWorkOrderOperations",
                "ReadLink": "{@odata.readLink}"
            }
        }
    	
    ],
    "ActionResult": {
        "_Name": "PRTCreate"
    },    
    "OnSuccess":"/SAPAssetManager/Rules/ApplicationEvents/AutoSync/actions/PRTEquipmentCreateSuccessWithAutoSync.js",
    "OnFailure": "/ZDSBSSAM/Rules/Operations/PRT/ZPRTCreateOnFailure.js",
    "ValidationRule": "/ZDSBSSAM/Rules/Workorders/Operations/PRT/CreateUpdate/ZPRTEquipmentCreateUpdateValidation.js",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : "  "
}
