{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/UpdateEntityFailureMessage.action",
	"Target": {
		"EntitySet": "MyNotificationItemCauses",
		"Service": "/SAPAssetManager/Services/AssetManager.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"CauseText": "#Control:CauseDescription/#Value",
		"CauseCodeGroup": "/SAPAssetManager/Rules/Notifications/GroupLstPkrValue.js",
		"CauseCode": "/SAPAssetManager/Rules/Notifications/CodeLstPkrValue.js"
	},
	"Headers": {
		"OfflineOData.TransactionID": "/SAPAssetManager/Rules/Notifications/NotificationItemCauseTaskActivityParentID.js"
	}
}